version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcontrib:0.0.1
    ports:
      - "10000:10000"
    command: ./ghcontrib --github_token ${GITHUB_TOKEN}
